all:
  vars:
    ansible_user: root
    ansible_port: 8090
  children:
    single-node:
      hosts:
        Rahbia-template:
        rahbia-services:
          DISK_SIZE: 100
          DATASTORE_NAME: SSD-SAMSUNG-4T-2
          MEMORY_SIZE: 8192
          CPU_SIZE: 4
          IP_ADDRESS: 192.168.200.101
          VM_FOLDER: RahBia-Live-Coding
          SSH_JUMP: "ssh -W %h:%p -q labe-amoo"
        rahbia-runner:
          DISK_SIZE: 30
          DATASTORE_NAME: SSD-SAMSUNG-4T-1
          MEMORY_SIZE: 4096
          CPU_SIZE: 2
          IP_ADDRESS: 192.168.200.102
          VM_FOLDER: RahBia-Live-Coding
          SSH_JUMP: "ssh -W %h:%p -q labe-amoo"
        rahbia-voting-app:
          DISK_SIZE: 30
          DATASTORE_NAME: SSD-SAMSUNG-4T-2
          MEMORY_SIZE: 4096
          CPU_SIZE: 4
          IP_ADDRESS: 192.168.200.103
          VM_FOLDER: RahBia-Live-Coding
          SSH_JUMP: "ssh -W %h:%p -q labe-amoo"
        development:
          DISK_SIZE: 30
          DATASTORE_NAME: SSD-SAMSUNG-4T-2
          MEMORY_SIZE: 4096
          CPU_SIZE: 4
          IP_ADDRESS: 192.168.200.104
          VM_FOLDER: RahBia-Live-Coding
          SSH_JUMP: "ssh -W %h:%p -q labe-amoo"
        production:
          DISK_SIZE: 30
          DATASTORE_NAME: SSD-SAMSUNG-4T-2
          MEMORY_SIZE: 4096
          CPU_SIZE: 4
          IP_ADDRESS: 192.168.200.105
          VM_FOLDER: RahBia-Live-Coding
          SSH_JUMP: "ssh -W %h:%p -q labe-amoo"
