version: "3.8"

networks:
  app_net:
    name: app_net
    driver: bridge
    external: true
  web_net:
    name: web_net
    driver: bridge
    external: true
services:
  pyapp:
    #    image: ${REPOSITORY_NAME}/${IMAGE_DIRECTORY_NAME}/app-py:${VERSION}
    image: app.py
    restart: ${RESTART_POLICY}
    container_name: pyapp-${HOSTNAME}
    hostname: pyapp-${HOSTNAME}
    ports:
      - ${EXTERNAL_PORT}:1888
    networks:
      - app_net
      - web_net
        #    command: python app.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1888/get"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
