---
service_dir: "{{ project_dir }}/nexus"

# nexus image tag
nexus_image_tag: 3.77.1

# nexus domain
nexus_main_domain: "repo.{{ main_domain }}"
nexus_main_url: "https://{{ nexus_main_domain }}"

delete_repository:
  - maven-snapshots
  - maven-public
  - maven-central
  - nuget-hosted
  - maven-releases
  - nuget-group
  - nuget.org-proxy

create_blob:
  - docker

anonymous_config:
  enabled: false
  userId: anonymous
  realmName: NexusAuthorizingRealm

role:
  id: repo_admin
  name: repo_admin
  description: repository admin
  privileges: nx-repository-admin-*-*-*
  roles: nx-anonymous

user:
  id: repo
  first_name: repo
  last_name: repo
  email_address: iliya.aghchaei@gmail.com
  status: active
  roles_name: repo_admin

create_docker_repository:
  - name: "hub"
    blob: "docker"
    cleanup_policy: "docker"
    remote_url: "https://hub.hamdocker.ir"
    repo_port: "9091"
    index_type: "HUB"
    repo_domain: "hub.{{ main_domain }}"

  - name: "quay"
    blob: "docker"
    cleanup_policy: "docker"
    remote_url: "https://quay.io"
    repo_port: "9092"
    index_type: "REGISTRY"
    repo_domain: "quay.{{ main_domain }}"

  - name: "gcr"
    blob: "docker"
    cleanup_policy: "docker"
    remote_url: "https://gcr.io"
    repo_port: "9094"
    index_type: "REGISTRY"
    repo_domain: "gcr.{{ main_domain }}"

  - name: "github"
    blob: "docker"
    cleanup_policy: "docker"
    remote_url: "https://ghcr.io"
    repo_port: "9096"
    index_type: "REGISTRY"
    repo_domain: "github.{{ main_domain }}"
